# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/go-sb-testclient/main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X github.com/danstis/go-sb-testclient/internal/version.Version={{.Version}}
    binary: go-sb-testclient

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - config.json.example

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^(build|chore|ci|doc|docs|none|perf|refactor|skip|test)(\\(.*?\\))?:\\s?"
